version: '3.7'

services:
  frontend:
    image: marceloaguero/microservices-istio-frontend
    ports:
      - 80:80
    networks:
      - golang-demo
  service-rev-proxy:
    image: marceloaguero/microservices-istio-service-rev-proxy
    ports:
      - 8000:80
    networks:
      - golang-demo
  service-a:
    image: marceloaguero/microservices-istio-service-a
    networks:
      - golang-demo
  service-b:
    image: marceloaguero/microservices-istio-service-b
    networks:
      - golang-demo
  service-c:
    image: marceloaguero/microservices-istio-service-c
    networks:
      - golang-demo
    environment:
      MONGO_CONN: 'mongodb://mongodb:27017/admin'
  mongodb:
    image: mongo:latest
    networks:
      - golang-demo
    ports:
      - 27017:27017

networks:
  golang-demo:
    external: true

volumes:
  data: {}
